app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::resource('crypto', 'CryptoController');
Route::resource('crypto-port', 'CryptoPortController');
Route::resource('dashboard', 'DashboardController');

app/Models/Coin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Coin extends Model
{
    protected $table = 'coin';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'name',
        'symbol'
    ];
}

app/Models/CryptoPort.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CryptoPort extends Model
{
    protected $table = 'crypto_ports';
    protected $primaryKey = 'id';
    public $timestamps = true;

    protected $fillable = [
        'user_id',
        'crypto_id',
        'rate',
        'amount',
        'curency',
        'type'
    ];

    public function User()
    {
        return $this->hasOne(User::class,'id','user_id');
    }

    public function coin()
    {
        return $this->hasOne('App\Models\Coin','id','crypto_id');
    }
}

app/Models/Transection.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transection extends Model
{
    protected $table = 'transection';
    protected $primaryKey = 'id';
    protected $timestamps = true;

    protected $fillable = [
        'user_id',
        'currency_id',
        'rate',
        'amount',
        'type'
    ];

    public function User()
    {
        return $this->hasOne(User::class,'id','user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Model;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Models/Wallet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Wallet extends Model
{
    protected $table = 'wallet';
    protected $primaryKey = 'id';
    protected $timestamps = true;

    protected $fillable = [
        'user_id',
        'currency_id',
        'total',
        'type'
    ];

    public function User()
    {
        return $this->hasOne(User::class,'id','user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CryptoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use GuzzleHttp\Client;

class CryptoController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        return view('home');
    }

    public function show($crypto)
    {

        return view('crypto')->with(['crypto' => $crypto]);
    }
}

app/Http/Controllers/CryptoPortController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use GuzzleHttp\Client;
use App\Models\Coin;
use App\Models\CryptoPort;

class CryptoPortController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $client = new Client();
        $response = $client->request('get', 'https://api.coinmarketcap.com/v1/ticker/');
        $data['curentCoin'] = json_decode($response->getBody());

        $data['coin'] = Coin::get();
        $data['ports'] = CryptoPort::where('user_id', \Auth::user()->id)
            ->orderBy('crypto_id', 'asc')
            ->get()
            ->groupBy('crypto_id');
        return view('port.index')->with('data', $data);
    }

    public function show($crypto)
    {

        return view('port.index')->with(['crypto' => $crypto]);
    }

    public function store(Request $request)
    {
        if (!isAdmin()) {
            return response()->json([
                'status' => 500,
                'errors' => [
                    'message' => 'Permission is locked!'
                ]
            ]);
        }

        $coin = Coin::find($request->id);

        if ($coin) {
            $port = CryptoPort::create([
                'user_id' => \Auth::user()->id,
                'crypto_id' => $request->id,
                'rate' => $request->rate,
                'amount' => $request->amount,
                'curency' => $coin->symbol,
                'type' => $request->type
            ]);

            return response()->json([
                'status' => 200,
                'data' => $port
            ]);
        } else {
            return response()->json([
                'status' => 500,
                'errors' => []
            ]);
        }
        
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Models\User;

class DashboardController extends Controller
{

    public $perPage = 15;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (!isAdmin()) {
            return redirect('/');
        }
        $users = User::where('permission', 'user')->paginate($this->perPage);
        return view('dashboard')->with([
            'users' => $users
        ]);
    }

    public function update(Request $request, $id)
    {
        if ($request->has('status')) {
            User::where('id', $id)->update(['status' => $request->status]);
        }
        return redirect()->route('dashboard.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use GuzzleHttp\Client;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/crypto.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Feature coming soon!</h1>
            <div class="panel panel-default">
                <div class="panel-heading" id="coin-title"></div>

                <div class="panel-body">
                    <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#buy" aria-controls="buy" role="tab" data-toggle="tab">Buy</a></li>
                        <li role="presentation"><a href="#sell" aria-controls="sell" role="tab" data-toggle="tab">Sell</a></li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="buy">
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                    <div id="display-coin"></div>
                                </div>
                                <div class="col-sm-6 col-md-8">
                                    <form action="#" class="form-horizontal" method="post">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Balance :</label>
                                            <div class="col-sm-10 control-label">
                                                0
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="sell">
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                    <div id="display-coin"></div>
                                </div>
                                <div class="col-sm-6 col-md-8">
                                    <form action=""></form>
                                </div>
                            </div>
                        </div>
                      </div>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footer')
<script>
(function($){
    // Initial
     $.get('https://api.coinmarketcap.com/v1/ticker/{{ $crypto }}/', function(resp){
        console.log(resp)
        $('#coin-title').html(resp[0].name)
    }); 

})(jQuery)
</script>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
            	<div class="panel-body">
	        		<table class="table table-hover">
	        			<thead>
	        				<tr>
	        					<th style="text-align: center">No.</th>
	        					<th style="text-align: center">Name</th>
	        					<th style="text-align: center">Email</th>
	        					<th style="text-align: center">Status</th>
	        					<th style="text-align: center">Action</th>
	        				</tr>
	        			</thead>
	        			<tbody>
	        				<?php $perPage = $users->perPage(); ?>
	        				@foreach($users as $key => $user)
	        				<tr>
	        					<td>{{ isset($_GET['page']) ? $perPage + $key  + 1 : $key  + 1 }}</td>
	        					<td>{{ $user->name }}</td>
	        					<td>{{ $user->email }}</td>
	        					<td>{{ $user->status }}</td>
	        					<td>
	        						@if(!$user->status)
	        						<form action="{{ route('dashboard.update', $user->id) }}" method="POST">
	        							{!! csrf_field() !!}
                    					<input type="hidden" name="_method" value="PUT">
                    					<input type="hidden" name="status" value="1">
	        							<button type="submit" class="btn btn-primary">Active</button>
	        						</form>
	        						@else
	        						<form action="{{ route('dashboard.update', $user->id) }}" method="POST">
	        							{!! csrf_field() !!}
                    					<input type="hidden" name="_method" value="PUT">
                    					<input type="hidden" name="status" value="0">
	        							<button type="submit" class="btn btn-danger">Inactive</button>
	        						</form>
	        						@endif
	        					</td>
	        				</tr>
	        				@endforeach
	        			</tbody>
	        		</table>
	        		<div class="text-right">{{ $users->links() }}</div>
				</div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footer')
<script>
(function($){
    

})(jQuery)

</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" rel="stylesheet"/>

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Cryptoto
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    @if (!Auth::guest())
                    <!-- <li><a href="{{ url('/crypto') }}">Crypto</a></li> -->
                    <li><a href="{{ url('/crypto-port') }}">My Port</a></li>
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                @if(isAdmin())
                                <li><a href="{{ url('/dashboard') }}"><i class="fa fa-btn fa-dashboard"></i>Dashboard</a></li>
                                @endif
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
    <script>
        $(document).ready(function(){
            
        });
    </script>
    @yield('footer')
</body>
</html>

resources/views/port/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">My Portfolio</div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form class="form-inline" id="formPort">
                                <div class="form-group">
                                    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                                    <div class="input-group">
                                      <select name="crypto" id="crypto" class="form-control">
                                          <option value="">------</option>
                                          @foreach($data['coin'] as $coin)
                                          <option value="{{ $coin->name }}">{{ $coin->name .'/'. $coin->symbol }}</option>
                                          @endforeach
                                      </select>
                                    </div>
                                </div>
                                <button type="button" id="add-port" class="btn btn-primary">+ Add port</button>
                            </form>
                        </div>
                    </div>
                    <div class="row" id="panel-port">
                        @if(!empty($data['ports']))
                        @foreach($data['ports'] as $myPorts)
                        <div class="col-md-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">{{ $myPorts[0]->coin->name }}<span class="pull-right">{{ $data['curentCoin'][$myPorts[0]->crypto_id - 1]->price_usd}}</span></div>
                              <div class="panel-body">
                                <div>
                                    <ul class="list-group" id="list-{{ $myPorts[0]->id }}">
                                        <?php 
                                            $price = $data['curentCoin'][$myPorts[0]->crypto_id - 1]->price_usd;
                                        ?>
                                        @foreach($myPorts as $port)
                                        <?php $profit = $price - $port->rate; ?>
                                        <li class="list-group-item {{ $profit > 0 ? 'list-group-item-success' : 'list-group-item-danger' }}">
                                            <div class="row">
                                                <div class="col-md-3">Buy: {{ ($port->amount / $port->rate) }} {{ $port->curency }}</div>
                                                <div class="col-md-3">Rate: {{ $port->rate }} $</div>
                                                <div class="col-md-3">Amount: {{ $port->amount }} $</div>
                                                <div class="col-md-3">Profit: {{ $profit }} $</div>
                                            </div>
                                        </li>
                                        @endforeach
                                    </ul>
                                </div>
                                <div id="form-crypto-{{ $myPorts[0]->id }}">
                                    <form class="form-horizontal" id="crypto-currency-{{ $myPorts[0]->id }}">
                                        <div class="form-group">
                                            <label for="price-crypto-{{ $myPorts[0]->id }}" class="col-sm-2 control-label">Price per {{ $myPorts[0]->coin->name }}</label>
                                            <div class="col-sm-10">
                                              <input type="number" name="rate" class="form-control" id="price-crypto-{{ $myPorts[0]->id }}" placeholder="Price per {{ $myPorts[0]->coin->name }}" required="required" value="{{ $data['curentCoin'][$myPorts[0]->crypto_id - 1]->price_usd }}" onkeyup="actionCalculator({{ $myPorts[0]->id }})">
                                            </div>
                                          </div>
                                          <div class="form-group">
                                            <label for="total-crypto-{{ $myPorts[0]->id }}" class="col-sm-2 control-label">Total {{ $myPorts[0]->id }}</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <input type="number" name="total" class="form-control handle-keyUp" id="total-crypto-{{ $myPorts[0]->id }}" placeholder="Total" value="" required="required" onkeyup="actionCalculator({{ $myPorts[0]->id }})" min="0" step="1">
                                                    <div class="input-group-addon">$</div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="form-group">
                                            <label for="price-crypto-{{ $myPorts[0]->id }}" class="col-sm-2 control-label">You will receipt</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <input type="number" class="form-control" id="receipt-crypto-{{ $myPorts[0]->id }}" value="0" disabled>
                                                    <div class="input-group-addon">{{ $myPorts[0]->coin->symbol }}</div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                              <button type="button" class="btn btn-default" onclick="actionCreatePort({{ $myPorts[0]->id }})">Create</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                              </div>
                            </div>
                        </div>
                        @endforeach
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footer')
<script>
(function($){
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "positionClass": "toast-top-center",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "3000",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
      }
    $('#add-port').on('click', function () {
        var $btn = $(this).html('<i class="fa fa-refresh fa-spin"></i>')

        if ($('#crypto').val() !== '' ) {
            var name = $('#crypto').val();

            $.get('https://api.coinmarketcap.com/v1/ticker/' + name.replace(' ', '-').toLowerCase() + '/', function(resp){
                var crypto = resp[0];
                if ($('#form-crypto-' + crypto.rank ).val() === undefined) {
                    $('#panel-port').append(template(crypto))
                    $('#form-crypto-'+ crypto.rank).append(formTemplate(crypto)) 
                }
                clear() 
            });
        } else {
           clear()
        }
    });

})(jQuery)

function actionCreatePort(id) {
    var form = $('#crypto-currency-'+id);
    // $('#crypto-currency-'+id)[0].reset();
    var rate = form.find('input[name="rate"]').val();
    var amount = form.find('input[name="total"]').val();

    $.ajax({
        type: "POST",
        url: "{{ url('crypto-port') }}",
        data: {
          id,
          rate,
          amount,
          type: 'buy'
        },
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        success: (data) => {
            console.log(data)
            if (data.status == 200) {
                var list = '<li class="list-group-item">\n\
                    <div class="row">\n\
                        <div class="col-md-3">Buy: ' +data.data.amount / data.data.rate +' ' +data.data.curency +'</div>\n\
                        <div class="col-md-3">Rate: '+ data.data.rate +' $</div>\n\
                        <div class="col-md-3">Amount: '+ data.data.amount +' $</div>\n\
                        <div class="col-md-3">Profit: 0 $</div>\n\
                    </div>\n\
                </li>';
                $('#list-'+ data.data.crypto_id).append(list)
                form[0].reset()
            } else if (data.status == 500) {
                toastr["warning"](data.errors.message, "Warning");
            }
            
        }
    });

}

function actionCalculator(id) {
    var perPrice = $('#price-crypto-'+id).val();
    var total = $('#total-crypto-'+id).val();
    $('#receipt-crypto-'+id).val( total/perPrice );
}

function clear() {
    $('#crypto').val('')
    $('#add-port').html('+ Add port');
}

function template(crypto) {
    var {
        name,
        rank
    } = crypto
    return '<div class="col-md-12">\n\
        <div class="panel panel-default">\n\
          <div class="panel-heading">'+ name +'</div>\n\
          <div class="panel-body">\n\
            <div>\n\
                <ul class="list-group" id="list-'+ rank +'"></ul>\n\
            </div>\n\
            <div id="form-crypto-'+ rank +'"></div>\n\
          </div>\n\
        </div>\n\
    </div>';
}

function formTemplate(coin) {
    var {
        name,
        rank,
        price_usd,
        symbol
    } = coin
    return '<form class="form-horizontal" id="crypto-currency-'+ rank +'">\n\
      <div class="form-group">\n\
        <label for="price-crypto-'+ rank +'" class="col-sm-2 control-label">Price per '+ name +'</label>\n\
        <div class="col-sm-10">\n\
          <input type="number" name="rate" class="form-control" id="price-crypto-'+ rank +'" placeholder="Price per '+ name +'" required="required" value="'+ price_usd +'">\n\
        </div>\n\
      </div>\n\
      <div class="form-group">\n\
        <label for="total-crypto-'+ rank +'" class="col-sm-2 control-label">Total</label>\n\
        <div class="col-sm-10">\n\
            <div class="input-group">\n\
                <input type="number" name="total" class="form-control handle-keyUp" id="total-crypto-'+ rank +'" placeholder="Total" value="" required="required" onkeyup="actionCalculator('+ rank +')" min="0" step="1">\n\
                <div class="input-group-addon">$</div>\n\
            </div>\n\
        </div>\n\
      </div>\n\
      <div class="form-group">\n\
        <label for="price-crypto-'+ rank +'" class="col-sm-2 control-label">You will receipt</label>\n\
        <div class="col-sm-10">\n\
            <div class="input-group">\n\
                <input type="number" class="form-control" id="receipt-crypto-'+ rank +'" value="0" disabled>\n\
                <div class="input-group-addon">'+ symbol +'</div>\n\
            </div>\n\
        </div>\n\
      </div>\n\
      <div class="form-group">\n\
        <div class="col-sm-offset-2 col-sm-10">\n\
          <button type="button" class="btn btn-default" onclick="actionCreatePort('+rank+')">Create</button>\n\
        </div>\n\
      </div>\n\
    </form>';
}
</script>
@endsection